[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "infobim"
authors = [
    { name = "Elias Magalhães", email = "elias@brasidata.com" }
]
version = "0.2.0"
description = "InfoBIM"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ifcopenshell",
    "jinja2",
    "ontobdc>=0.11.0",
    "Pillow",
    "pyfiglet",
]

[project.scripts]
infobim = "infobim.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"infobim" = [
    "*.sh",
    "check/*.sh",
    "check/*.json",
    "check/infra/*/*.sh",
    "project/*.sh",
    "project/*.py",
    "context/**",
    "view/**",
    "module/**",
    "run/*.sh",
    "cli/**",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["infobim*"]
