"""Read and write the schedule workbook a container's datapackage maps.

One logical task is three rows in three sheets -- ``IfcTask``,
``IfcTaskTime`` and ``IfcRelSequence`` -- tied together by GlobalIds. Typing
those by hand is where a schedule quietly loses data: a mistyped GlobalId
raises nothing, it just makes the task vanish from the Gantt. This adapter
owns that wiring so no one has to type an id.

It never searches the container for a workbook. The container's
``.__ontobdc__/datapackage.json`` already declares which file holds the
schedule and which sheet holds each entity; that declaration is the
authority, and going around it would let this write to a different file than
the one the Surface reads.
"""
from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from openpyxl import load_workbook
from openpyxl.workbook.workbook import Workbook
from openpyxl.worksheet.worksheet import Worksheet

SCHEDULE_ENTITIES: Tuple[str, ...] = (
    "IfcWorkSchedule",
    "IfcTask",
    "IfcTaskTime",
    "IfcRelSequence",
)

MARKER_DIRECTORY: str = ".__ontobdc__"
DATAPACKAGE_FILE: str = "datapackage.json"


class ScheduleWorkbookError(Exception):
    """Raised when the container cannot serve a schedule to write into."""


class ScheduleWorkbookAdapter:
    """Append tasks to the schedule workbook declared by the container."""

    def __init__(self, container_path: Path) -> None:
        self.container_path: Path = Path(container_path).expanduser().resolve()
        self.datapackage_path: Path = self._locate_datapackage()

        descriptors: Dict[str, Dict[str, Any]] = self._schedule_descriptors()
        self.workbook_path: Path = self._workbook_path(descriptors)
        descriptors = self._complete_workbook_descriptors(descriptors)
        missing: List[str] = [
            entity for entity in ("IfcTask", "IfcTaskTime")
            if entity not in descriptors
        ]
        if missing:
            raise ScheduleWorkbookError(
                f"The datapackage at {self.datapackage_path} does not map "
                f"{' and '.join(missing)}. This container has no schedule to "
                "fill in yet."
            )

        self.sheet_names: Dict[str, str] = {
            entity: self._sheet_name(descriptor)
            for entity, descriptor in descriptors.items()
        }

    # ------------------------------------------------------------ discovery

    def _locate_datapackage(self) -> Path:
        directory: Path
        for directory in (self.container_path, *self.container_path.parents):
            candidate: Path = directory / MARKER_DIRECTORY / DATAPACKAGE_FILE
            if candidate.is_file():
                return candidate
        raise ScheduleWorkbookError(
            f"No {MARKER_DIRECTORY}/{DATAPACKAGE_FILE} found at "
            f"{self.container_path} or above it."
        )

    def _schedule_descriptors(self) -> Dict[str, Dict[str, Any]]:
        document: Any = json.loads(
            self.datapackage_path.read_text(encoding="utf-8")
        )
        found: Dict[str, Dict[str, Any]] = {}
        resource: Any
        for resource in document.get("resources") or []:
            if not isinstance(resource, dict):
                continue
            identifier: str = str(
                resource.get("entityIdentifier") or resource.get("name") or ""
            ).strip()
            entity: str
            for entity in SCHEDULE_ENTITIES:
                if identifier.lower() == entity.lower():
                    found[entity] = resource
        return found

    def _complete_workbook_descriptors(
        self,
        descriptors: Dict[str, Dict[str, Any]],
    ) -> Dict[str, Dict[str, Any]]:
        """Map related 4D sheets inside one declared workbook resource.

        Some datapackages describe every worksheet as its own resource;
        container datasets generated by InfoBIM describe the workbook once,
        as ``IfcWorkSchedule``. Both forms remain datapackage-authoritative:
        this method only accepts related entities that are actual sheets in
        the already-declared file and never searches for another workbook.
        """
        root_descriptor = descriptors.get("IfcWorkSchedule")
        if root_descriptor is None:
            return descriptors

        try:
            workbook = load_workbook(
                filename=str(self.workbook_path),
                read_only=True,
                data_only=True,
            )
        except (OSError, ValueError) as error:
            raise ScheduleWorkbookError(
                f"Could not inspect the mapped workbook: {self.workbook_path}"
            ) from error
        try:
            available = set(workbook.sheetnames)
        finally:
            workbook.close()

        completed = dict(descriptors)
        for entity in SCHEDULE_ENTITIES:
            if entity in completed or entity not in available:
                continue
            descriptor = dict(root_descriptor)
            dialect = dict(descriptor.get("dialect") or {})
            excel = dict(dialect.get("excel") or {})
            excel["sheet"] = entity
            dialect["excel"] = excel
            descriptor["dialect"] = dialect
            descriptor["entityIdentifier"] = entity
            completed[entity] = descriptor
        return completed

    @staticmethod
    def _sheet_name(descriptor: Dict[str, Any]) -> str:
        excel: Dict[str, Any] = (
            (descriptor.get("dialect") or {}).get("excel") or {}
        )
        return str(excel.get("sheet") or descriptor.get("name") or "").strip()

    def _workbook_path(self, descriptors: Dict[str, Dict[str, Any]]) -> Path:
        paths = {
            (self.datapackage_path.parent / str(d.get("path") or "")).resolve()
            for d in descriptors.values()
            if d.get("path")
        }
        if not paths:
            raise ScheduleWorkbookError(
                "This container has no schedule resource with a declared 'path'."
            )
        if len(paths) > 1:
            listed: str = "\n  ".join(str(path) for path in sorted(paths))
            raise ScheduleWorkbookError(
                "The schedule sheets are spread across more than one file:\n  "
                f"{listed}\nThis command only writes to a single workbook."
            )
        path: Path = paths.pop()
        if not path.is_file():
            raise ScheduleWorkbookError(
                f"The datapackage points at a file that does not exist: {path}"
            )
        return path

    # -------------------------------------------------------------- reading

    def open_workbook(self) -> Workbook:
        try:
            return load_workbook(filename=str(self.workbook_path))
        except PermissionError as error:
            raise ScheduleWorkbookError(
                f"Could not open {self.workbook_path.name} for writing. "
                "Close the workbook in Excel and try again."
            ) from error

    def tasks(self) -> List[Dict[str, str]]:
        """Every task, joined to its time row, ready for display."""
        workbook: Workbook = self.open_workbook()
        try:
            task_rows = self.records(workbook, "IfcTask")
            time_rows = {
                str(row.get("GlobalId") or ""): row
                for row in self.records(workbook, "IfcTaskTime")
            }
        finally:
            workbook.close()

        listed: List[Dict[str, str]] = []
        task_row: Dict[str, Any]
        for task_row in task_rows:
            time_row: Dict[str, Any] = time_rows.get(
                str(task_row.get("TaskTime") or ""), {}
            )
            listed.append({
                "id": str(task_row.get("GlobalId") or ""),
                "wbs": str(task_row.get("Identification") or ""),
                "name": str(task_row.get("Name") or ""),
                "start": as_date_text(time_row.get("ScheduleStart")),
                "finish": as_date_text(time_row.get("ScheduleFinish")),
                "actual_start": as_date_text(time_row.get("ActualStart")),
                "actual_finish": as_date_text(time_row.get("ActualFinish")),
                "percent": str(time_row.get("PercentComplete") or ""),
                "milestone": str(task_row.get("IsMilestone") or ""),
            })
        listed.sort(key=lambda row: wbs_sort_key(row["wbs"]))
        return listed

    def records(self, workbook: Workbook, entity: str) -> List[Dict[str, Any]]:
        sheet_name: str = self.sheet_names.get(entity, "")
        if not sheet_name or sheet_name not in workbook.sheetnames:
            return []
        worksheet: Worksheet = workbook[sheet_name]
        rows = worksheet.iter_rows(values_only=True)
        try:
            header: List[str] = [
                str(cell).strip() if cell is not None else ""
                for cell in next(rows)
            ]
        except StopIteration:
            return []

        records: List[Dict[str, Any]] = []
        raw: Any
        for raw in rows:
            record: Dict[str, Any] = {
                column: value
                for column, value in zip(header, raw)
                if column and value is not None
            }
            if record:
                records.append(record)
        return records

    # -------------------------------------------------------------- writing

    def append(
        self,
        workbook: Workbook,
        entity: str,
        values: Dict[str, Any],
    ) -> None:
        """Append a row, matching the sheet's own header rather than order.

        The workbook in the container was authored by whoever set the project
        up; its columns may sit in any order and may not include every field
        this command can record. Matching by header name means the sheet
        keeps its shape, and a column that is genuinely missing is added
        rather than demanded -- recording a new fact should never require
        restructuring the file first.
        """
        sheet_name: str = self.sheet_names.get(entity, "")
        if not sheet_name:
            return
        if sheet_name not in workbook.sheetnames:
            workbook.create_sheet(sheet_name).append(list(values))

        worksheet: Worksheet = workbook[sheet_name]
        header: List[str] = self._header(worksheet)
        self._ensure_columns(worksheet, header, values)
        worksheet.append([values.get(column) for column in header])

    def update_task_time(
        self,
        workbook: Workbook,
        task_time_id: str,
        values: Dict[str, Any],
    ) -> bool:
        sheet_name: str = self.sheet_names.get("IfcTaskTime", "")
        if not sheet_name or sheet_name not in workbook.sheetnames:
            return False

        worksheet: Worksheet = workbook[sheet_name]
        header: List[str] = self._header(worksheet)
        self._ensure_columns(worksheet, header, values)
        if "GlobalId" not in header:
            return False

        identifier_column: int = header.index("GlobalId") + 1
        row_index: int
        for row_index in range(2, worksheet.max_row + 1):
            current: Any = worksheet.cell(
                row=row_index, column=identifier_column
            ).value
            if str(current or "").strip() != task_time_id:
                continue
            column: str
            value: Any
            for column, value in values.items():
                worksheet.cell(
                    row=row_index,
                    column=header.index(column) + 1,
                    value=value,
                )
            return True
        return False

    @staticmethod
    def _header(worksheet: Worksheet) -> List[str]:
        return [
            str(cell.value).strip() if cell.value is not None else ""
            for cell in worksheet[1]
        ]

    @staticmethod
    def _ensure_columns(
        worksheet: Worksheet,
        header: List[str],
        values: Dict[str, Any],
    ) -> None:
        column: str
        for column in values:
            if column not in header:
                header.append(column)
                worksheet.cell(row=1, column=len(header), value=column)

    @staticmethod
    def next_identifier(existing: List[str], prefix: str) -> str:
        used = set(existing)
        index: int = 1
        while f"{prefix}{index}" in used:
            index += 1
        return f"{prefix}{index}"


# ---------------------------------------------------------------- helpers

def wbs_sort_key(value: Any) -> List[Any]:
    """Order 1.9 before 1.10, which is what a schedule means by those."""
    parts: List[Any] = []
    part: str
    for part in str(value or "").split("."):
        part = part.strip()
        parts.append((0, int(part)) if part.isdigit() else (1, part))
    return parts


def as_date_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (dt.datetime, dt.date)):
        return value.strftime("%Y-%m-%d")
    return str(value)[:10]


def parse_date(value: Any) -> Optional[dt.datetime]:
    """Accept what an ``<input type=date>`` sends and what a person types."""
    if value is None:
        return None
    text: str = str(value).strip()
    if not text:
        return None
    pattern: str
    for pattern in ("%Y-%m-%d", "%d/%m/%Y", "%d/%m/%y", "%d-%m-%Y"):
        try:
            return dt.datetime.strptime(text, pattern)
        except ValueError:
            continue
    try:
        day, month = text.split("/")
        return dt.datetime(dt.date.today().year, int(month), int(day))
    except (ValueError, TypeError) as error:
        raise ValueError(f"Data não reconhecida: {text}") from error


def parse_percent(value: Any) -> Optional[int]:
    text: str = str(value or "").strip().rstrip("%").replace(",", ".")
    if not text:
        return None
    try:
        number: float = float(text)
    except ValueError as error:
        raise ValueError(f"Percentual inválido: {value}") from error
    return max(0, min(100, int(round(number))))


def today_at_midnight() -> dt.datetime:
    return dt.datetime.combine(dt.date.today(), dt.time())
